import type { VaultDocument } from "@/content/projects/vault/types";

export const forgeDocuments: VaultDocument[] = [
    {
    slug: "architecture",
    title: "Forge Architecture Brief",
    abstract: "A structural overview of the Forge system architecture and its core components.",
    category: "Platform Strategy",
    thumbnail: "/thumbnails/vault/forge/architecture.jpg",
    mdx: "/content/projects/vault/forge/documents/architecture.mdx",
    pdf: "/projects/vault/forge/FORGE — Vision.pdf",
    ndaNote: "The PDF provides a high-level overview only. Detailed technical, commercial, or proprietary materials are available under NDA. To request access, email Elliott@Webb.Systems with your name, organization, and intended use; requests are reviewed within 3 business days.",
  },
  {
    slug: "one-pager",
    title: "Forge One-Pager",
    abstract: "A concise overview of the Forge platform vision and strategic intent.",
    category: "Platform Strategy",
    thumbnail: "/thumbnails/vault/forge/one-pager.jpg",
    mdx: "/content/projects/vault/forge/documents/one-pager.mdx",
    pdf: "/projects/vault/forge/FORGE — One-Pager.pdf",
    ndaNote: "The PDF provides a high-level overview only. Detailed technical, commercial, or proprietary materials are available under NDA. To request access, email Elliott@Webb.Systems with your name, organization, and intended use; requests are reviewed within 3 business days.",
  },
  {
    slug: "executive-overview",
    title: "Forge Executive Overview",
    abstract: "A leadership-facing summary of the Forge platform, its goals, and its value.",
    category: "Platform Strategy",
    thumbnail: "/thumbnails/vault/forge/executive-summary.jpg",
    mdx: "/content/projects/vault/forge/documents/executive-summary.mdx",
    pdf: "/projects/vault/forge/FORGE — Overview.pdf",
    ndaNote: "The PDF provides a high-level overview only. Detailed technical, commercial, or proprietary materials are available under NDA. To request access, email Elliott@Webb.Systems with your name, organization, and intended use; requests are reviewed within 3 business days.",
  },
  {
    slug: "founder-letter",
    title: "Forge — Founder Letter",
    abstract: "A foundational letter outlining the vision and philosophy behind Forge.",
    category: "Foundation",
    mdx: "/content/projects/vault/forge/documents/founder-letter.mdx",
    pdf: "/projects/vault/forge/FORGE — Founder Letter.pdf",
    ndaNote: "The PDF provides a high-level overview only. Detailed technical, commercial, or proprietary materials are available under NDA. To request access, email Elliott@Webb.Systems with your name, organization, and intended use; requests are reviewed within 3 business days.",
  },
  {
    slug: "systemic-drift",
    title: "Forge — Systemic Drift",
    abstract: "An analysis of systemic drift and how Forge prevents long-term degradation.",
    category: "Foundation",
    mdx: "/content/projects/vault/forge/documents/systemic-drift.mdx",
    pdf: "/projects/vault/forge/FORGE — Systemic Drift.pdf",
    ndaNote: "The PDF provides a high-level overview only. Detailed technical, commercial, or proprietary materials are available under NDA. To request access, email Elliott@Webb.Systems with your name, organization, and intended use; requests are reviewed within 3 business days.",
  },
  {
    slug: "coherence",
    title: "Forge — Coherence",
    abstract: "A discussion of systemic coherence and how Forge maintains structural clarity.",
    category: "Foundation",
    mdx: "/content/projects/vault/forge/documents/coherence.mdx",
    pdf: "/projects/vault/forge/FORGE — Coherence.pdf",
    ndaNote: "The PDF provides a high-level overview only. Detailed technical, commercial, or proprietary materials are available under NDA. To request access, email Elliott@Webb.Systems with your name, organization, and intended use; requests are reviewed within 3 business days.",
  },
  {
    slug: "predictability",
    title: "Forge — Predictability",
    abstract: "Why predictable systems matter and how Forge enforces them.",
    category: "Engineering",
    mdx: "/content/projects/vault/forge/documents/predictability.mdx",
    pdf: "/projects/vault/forge/FORGE — Predictability.pdf",
    ndaNote: "The PDF provides a high-level overview only. Detailed technical, commercial, or proprietary materials are available under NDA. To request access, email Elliott@Webb.Systems with your name, organization, and intended use; requests are reviewed within 3 business days.",
  },
  {
    slug: "traceability",
    title: "Forge — Traceability",
    abstract: "A deep dive into traceability and how Forge maintains clear lineage of decisions.",
    category: "Engineering",
    mdx: "/content/projects/vault/forge/documents/traceability.mdx",
    pdf: "/projects/vault/forge/FORGE — Traceability.pdf",
    ndaNote: "The PDF provides a high-level overview only. Detailed technical, commercial, or proprietary materials are available under NDA. To request access, email Elliott@Webb.Systems with your name, organization, and intended use; requests are reviewed within 3 business days.",
  },
  {
    slug: "iteration",
    title: "Forge — Iteration",
    abstract: "How Forge supports rapid iteration without sacrificing stability.",
    category: "Engineering",
    mdx: "/content/projects/vault/forge/documents/iteration.mdx",
    pdf: "/projects/vault/forge/FORGE — Iteration.pdf",
    ndaNote: "The PDF provides a high-level overview only. Detailed technical, commercial, or proprietary materials are available under NDA. To request access, email Elliott@Webb.Systems with your name, organization, and intended use; requests are reviewed within 3 business days.",
  },
  {
    slug: "technical-dependency",
    title: "Forge — Technical Dependency",
    abstract: "How Forge reduces unnecessary dependencies and increases system resilience.",
    category: "Design",
    mdx: "/content/projects/vault/forge/documents/technical-dependency.mdx",
    pdf: "/projects/vault/forge/FORGE — Technical Dependency.pdf",
    ndaNote: "The PDF provides a high-level overview only. Detailed technical, commercial, or proprietary materials are available under NDA. To request access, email Elliott@Webb.Systems with your name, organization, and intended use; requests are reviewed within 3 business days.",
  },
    {
    slug: "designer-sovereignty",
    title: "Forge — Designer Sovereignty",
    abstract: "Why Forge protects designer intent and prevents systemic drift.",
    category: "Design",
    mdx: "/content/projects/vault/forge/documents/designer-sovereignty.mdx",
    pdf: "/projects/vault/forge/FORGE — Designer Sovereignty.pdf",
    ndaNote: "The PDF provides a high-level overview only. Detailed technical, commercial, or proprietary materials are available under NDA. To request access, email Elliott@Webb.Systems with your name, organization, and intended use; requests are reviewed within 3 business days.",
  },
  {
    slug: "portability",
    title: "Forge — Portability",
    abstract: "A look at how Forge enables systems to move across contexts without breaking.",
    category: "Strategy",
    mdx: "/content/projects/vault/forge/documents/portability.mdx",
    pdf: "/projects/vault/forge/FORGE — Portability.pdf",
    ndaNote: "The PDF provides a high-level overview only. Detailed technical, commercial, or proprietary materials are available under NDA. To request access, email Elliott@Webb.Systems with your name, organization, and intended use; requests are reviewed within 3 business days.",
  },
  {
    slug: "adaptability",
    title: "Forge — Adaptability",
    abstract: "How Forge enables adaptable systems that evolve with creators and constraints.",
    category: "Strategy",
    mdx: "/content/projects/vault/forge/documents/adaptability.mdx",
    pdf: "/projects/vault/forge/FORGE — Adaptability.pdf",
    ndaNote: "The PDF provides a high-level overview only. Detailed technical, commercial, or proprietary materials are available under NDA. To request access, email Elliott@Webb.Systems with your name, organization, and intended use; requests are reviewed within 3 business days.",
  },
];
